[env]
platform = espressif32
board = featheresp32
framework = arduino
board_build.f_cpu = 240000000L
monitor_speed = 115200
upload_speed = 921600
monitor_filters = send_on_enter, colorize, time

[env:radio-test]
build_src_filter = -<*> +<radio-test/*>